"""Fetch audio deepfake training data (Audio Step 1).

Primary source: ASVspoof 2019 Logical Access (LA) train + dev partitions from
the official academic mirror (datashare.ed.ac.uk, the asvspoof.org download
endpoint — ODC-By 1.0 research licence). The official zip is ~7.6 GB and the
mirror throttles to ~180 KB/s, so the fetch chain also accepts a research
HuggingFace parquet mirror of the SAME ASVspoof 2019 LA data, used for
hackathon-scale runs:

    source chain (--source auto): official -> hf_mirror -> wavefake -> espeak

  1. official   — https://datashare.ed.ac.uk/.../LA.zip (selective zip extract,
                  capped per class by --max-utterances)
  2. hf_mirror  — HF dataset Bisher/ASVspoof_2019_LA parquet shards (train ->
                  LA train, validation -> LA dev); bona fide = system_id "-",
                  spoof = attack id A01..A06 (LA train/dev contain only the six
                  seen attacks; A07-A19 are the unseen eval attacks)
  3. wavefake   — WaveFake HuggingFace mirror (fake = neural-vocoder TTS of
                  LJSpeech text; real = LJSpeech bona fide)
  4. espeak_ng  — LAST RESORT: synthetic fakes synthesised locally with
                  espeak-ng against any bona fide audio already cached on
                  disk; provenance status becomes synthetic_fallback

Optional modern-TTS augmentation behind --augment-piper: synthesise neural
VITS fakes offline with piper-tts from 200 public-domain sentences (labelled
fake, subclass piper_tts). If the package or voice download cannot be
installed/used, the script warns and skips — it never crashes.

Real-world gate split (NEVER trained on, evaluation only):
    datasets/media/real_world_audio/fake/  user-contributed ElevenLabs clips
    datasets/media/real_world_audio/real/  user voice memos
A copy of the ElevenLabs clip ercv.mp3 is placed in fake/ when available.

Outputs:
    ml/data/audio/manifest.csv            filepath,label,subclass,partition,source
    ml/data/audio/provenance.json         per-source provenance (licence+status)
    ml/data/audio/asvspoof2019/<partition>/<subclass>/*.flac
    evidence/media/real_speech.wav        one bona fide ASVspoof dev utterance

Usage (from the backend directory):
    uv run python -m ml.fetch_audio_data --max-utterances 4000
    uv run python -m ml.fetch_audio_data --source hf_mirror --augment-piper
"""

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))  # backend/ on sys.path for every launch style

import argparse
import csv
import hashlib
import io
import json
import shutil
import subprocess
import sys
import time
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

ML_DIR = Path(__file__).resolve().parent
DATA_DIR = ML_DIR / "data" / "audio"
RAW_DIR = DATA_DIR / "raw"
ASVSPOOF_DIR = DATA_DIR / "asvspoof2019"
REPO_ROOT = ML_DIR.parents[1]
DATASETS_MEDIA = REPO_ROOT / "datasets" / "media"
REAL_WORLD_DIR = DATASETS_MEDIA / "real_world_audio"
EVIDENCE_MEDIA = REPO_ROOT / "evidence" / "media"

HF_MIRROR = "https://huggingface.co/datasets/Bisher/ASVspoof_2019_LA/resolve/main/data"
WAVEFAKE_HF = "https://huggingface.co/datasets/DeepFense/WaveFake/resolve/main/wavefake.parquet"
OFFICIAL_URL = (
    "https://datashare.ed.ac.uk/server/api/core/bitstreams/"
    "a9f87c35-f055-4015-80e2-2fdff0d46269/content"
)
# LA train/dev contain attacks A01-A06 only (A07-A19 are the unseen eval attacks).
LA_ATTACKS = [f"A{i:02d}" for i in range(1, 7)]
ERCV_CANDIDATES = [
    Path("/home/chandan/Downloads/New Folder/ercv.mp3"),
    REPO_ROOT / "datasets" / "media" / "ercv.mp3",
    REPO_ROOT.parent / "Downloads" / "ercv.mp3",
]
PUBLIC_DOMAIN_SENTENCES = [
    # Project Gutenberg / public-domain openings (deterministic pool of 200 is
    # generated by combining these openings with numbered variants).
    "The quick brown fox jumps over the lazy dog.",
    "It was the best of times, it was the worst of times.",
    "Call me Ishmael.",
    "All happy families are alike; each unhappy family is unhappy in its own way.",
    "The past is a foreign country; they do things differently there.",
    "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.",
    "In the beginning the Universe was created.",
    "The sky above the port was the color of television, tuned to a dead channel.",
    "I am an invisible man.",
    "He was an old man who fished alone in a skiff in the Gulf Stream.",
    "Mother died today.",
    "It was a bright cold day in April, and the clocks were striking thirteen.",
    "Somewhere in la Mancha, in a place whose name I do not care to remember.",
    "Once upon a time and a very good time it was there was a moocow coming down along the road.",
    "It was a dark and stormy night.",
    "Many years later, as he faced the firing squad, Colonel Aureliano Buendia was to remember that distant afternoon.",
    "The sun shone, having no alternative, on the nothing new.",
    "If you really want to hear about it, the first thing you'll probably want to know is where I was born.",
    "Stately, plump Buck Mulligan came from the stairhead, bearing a bowl of lather.",
    "124 was spiteful. Full of Baby's venom.",
]
# 200 synthesis sentences: cycle the openings with distinct numbered tails.
PIPER_SENTENCES = [f"Take {i}. {PUBLIC_DOMAIN_SENTENCES[i % len(PUBLIC_DOMAIN_SENTENCES)]}" for i in range(200)]


def sha256_of(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        while chunk := fh.read(1 << 20):
            digest.update(chunk)
    return digest.hexdigest()


def download(url: str, dest: Path, timeout: int = 600) -> Path:
    """Stream a URL to disk with a one-line progress indicator."""
    dest.parent.mkdir(parents=True, exist_ok=True)
    started = time.time()
    with urllib.request.urlopen(url, timeout=timeout) as resp, dest.open("wb") as out:
        total = int(resp.headers.get("Content-Length", 0)) or None
        done = 0
        while chunk := resp.read(1 << 22):
            out.write(chunk)
            done += len(chunk)
            if total:
                mbps = done / max(time.time() - started, 1e-6) / 1e6
                print(f"\r  {dest.name}: {done / 1e9:.2f}/{total / 1e9:.2f} GB ({mbps:.1f} MB/s)", end="", flush=True)
    print(f"\r  {dest.name}: downloaded {done / 1e9:.2f} GB in {time.time() - started:.0f}s")
    return dest


# ---------------------------------------------------------------------------
# Source 1: official datashare.ed.ac.uk LA.zip
# ---------------------------------------------------------------------------

def fetch_official(max_utterances: int) -> tuple[list[dict], dict | None]:
    """ASVspoof 2019 LA from the official archive (selective extraction)."""
    import zipfile

    zip_path = RAW_DIR / "LA.zip"
    if not zip_path.exists():
        print("  downloading official LA.zip (~7.6 GB — the official mirror throttles; "
              "use --source hf_mirror for the research parquet mirror)")
        download(OFFICIAL_URL, zip_path, timeout=120)
    protocols = {
        "train": "ASVspoof2019_LA.cm.train.trn.txt",
        "dev": "ASVspoof2019_LA.cm.dev.trl.txt",
    }
    rows: list[dict] = []
    with zipfile.ZipFile(zip_path) as zf:
        names = set(zf.namelist())
        for partition, protocol in protocols.items():
            protocol_name = next((n for n in names if n.endswith(protocol)), None)
            if protocol_name is None:
                raise FileNotFoundError(f"protocol {protocol} not in archive")
            per_class: dict[str, int] = {"bonafide": 0, "spoof": 0}
            for line in zf.read(protocol_name).decode().strip().splitlines():
                parts = line.split()
                # utterance_id partition -(attack or '-')- label
                utterance_id, attack, label = parts[0], parts[2], parts[3]
                cls = "bonafide" if label == "bonafide" else "spoof"
                if per_class[cls] >= max_utterances:
                    continue
                subclass = cls if cls == "bonafide" else attack
                member = next(
                    (n for n in names if n.endswith(f"{utterance_id}.flac")), None
                )
                if member is None:
                    continue
                dest = ASVSPOOF_DIR / partition / ("bonafide" if cls == "bonafide" else "spoof") / f"{utterance_id}.flac"
                if not dest.exists():
                    dest.parent.mkdir(parents=True, exist_ok=True)
                    dest.write_bytes(zf.read(member))
                rows.append(
                    {
                        "filepath": str(dest.relative_to(ML_DIR.parent)),
                        "label": 0 if cls == "bonafide" else 1,
                        "subclass": f"asvspoof2019_{partition}_{subclass}",
                        "partition": partition,
                        "source": "asvspoof2019_official",
                    }
                )
                per_class[cls] += 1
    provenance = {
        "source": "asvspoof2019_official",
        "url": OFFICIAL_URL,
        "licence": "ODC-By 1.0 (ASVspoof 2019, academic/research use)",
        "status": "fetched",
        "sha256": sha256_of(zip_path),
        "rows": len(rows),
    }
    return rows, provenance


# ---------------------------------------------------------------------------
# Source 2: HF parquet mirror of the same ASVspoof 2019 LA data
# ---------------------------------------------------------------------------

def fetch_hf_mirror(max_utterances: int) -> tuple[list[dict], dict | None]:
    """ASVspoof 2019 LA via the HuggingFace parquet research mirror.

    train-*.parquet -> LA train, validation-*.parquet -> LA dev.
    bonafide = system_id '-' ; spoof = attack system id (A01..A06).
    """
    import pyarrow.parquet as pq
    import soundfile as sf

    partitions = {
        "train": RAW_DIR / "la_train.parquet",
        "dev": RAW_DIR / "la_dev.parquet",
    }
    if not partitions["train"].exists():
        download(f"{HF_MIRROR}/train-00000-of-00001.parquet", partitions["train"])
    if not partitions["dev"].exists():
        download(f"{HF_MIRROR}/validation-00000-of-00001.parquet", partitions["dev"])

    rows: list[dict] = []
    for partition, parquet_path in partitions.items():
        attack_counts: dict[str, int] = {}
        bona_count = 0
        reader = pq.ParquetFile(parquet_path)
        for batch in reader.iter_batches(batch_size=256, columns=["speaker_id", "audio_file_name", "audio", "system_id"]):
            columns = {name: batch.column(name).to_pylist() for name in batch.schema.names}
            for speaker, file_name, audio, system_id in zip(
                columns["speaker_id"], columns["audio_file_name"], columns["audio"], columns["system_id"]
            ):
                bonafide = str(system_id).strip() in ("-", "")
                if bonafide:
                    if bona_count >= max_utterances:
                        continue
                else:
                    if attack_counts.get(str(system_id), 0) >= max_utterances // len(LA_ATTACKS) + 1:
                        continue
                subclass = "bonafide" if bonafide else str(system_id)
                if not file_name.endswith(".flac"):
                    file_name = f"{file_name}.flac"
                dest = ASVSPOOF_DIR / partition / subclass / file_name
                if not dest.exists():
                    dest.parent.mkdir(parents=True, exist_ok=True)
                    try:
                        raw = io.BytesIO(audio["bytes"])
                        with sf.SoundFile(raw) as handle:
                            signal = handle.read(dtype="float32", always_2d=True).mean(axis=1)
                            rate = handle.samplerate
                        sf.write(dest, signal, rate, format="FLAC")
                    except Exception as exc:
                        print(f"    WARN skipping unreadable utterance {file_name}: {exc}")
                        continue
                if bonafide:
                    bona_count += 1
                else:
                    attack_counts[str(system_id)] = attack_counts.get(str(system_id), 0) + 1
                rows.append(
                    {
                        "filepath": str(dest.relative_to(ML_DIR.parent)),
                        "label": 0 if bonafide else 1,
                        "subclass": f"asvspoof2019_{partition}_{subclass}",
                        "partition": partition,
                        "source": "asvspoof2019_hf_mirror",
                    }
                )
            if bona_count >= max_utterances and all(
                c >= max_utterances // len(LA_ATTACKS) + 1 for c in attack_counts.values()
            ) and len(attack_counts) >= len(LA_ATTACKS):
                break
    provenance = {
        "source": "asvspoof2019_hf_mirror",
        "url": f"{HF_MIRROR}/train-00000-of-00001.parquet (+validation)",
        "licence": "ODC-By 1.0 — ASVspoof 2019 LA research mirror (same utterances as the official archive)",
        "status": "fetched",
        "sha256": sha256_of(partitions["train"]),
        "sha256_dev": sha256_of(partitions["dev"]),
        "rows": len(rows),
    }
    return rows, provenance


# ---------------------------------------------------------------------------
# Source 3: WaveFake HF mirror
# ---------------------------------------------------------------------------

def fetch_wavefake(max_utterances: int) -> tuple[list[dict], dict | None]:
    """WaveFake mirror: neural-vocoder fakes of LJSpeech + LJSpeech bona fide."""
    import pyarrow.parquet as pq
    import soundfile as sf

    parquet_path = RAW_DIR / "wavefake.parquet"
    download(WAVEFAKE_HF, parquet_path)
    rows: list[dict] = []
    reader = pq.ParquetFile(parquet_path)
    audio_col, label_col = None, None
    for batch in reader.iter_batches(batch_size=64):
        names = set(batch.schema.names)
        audio_col = next((n for n in names if "audio" in n.lower() or "bytes" in n.lower()), None)
        label_col = next((n for n in names if "label" in n.lower()), None)
        break
    if audio_col is None:
        raise FileNotFoundError("WaveFake mirror parquet has no audio column; cannot use fallback")
    for batch in reader.iter_batches(batch_size=64):
        columns = {name: batch.column(name).to_pylist() for name in batch.schema.names}
        for index, audio in enumerate(columns[audio_col]):
            fake = bool(columns[label_col][index]) if label_col else False
            if len([r for r in rows if r["label"] == (1 if fake else 0)]) >= max_utterances:
                continue
            dest = DATA_DIR / "wavefake" / ("fake" if fake else "real") / f"wf_{len(rows):06d}.flac"
            dest.parent.mkdir(parents=True, exist_ok=True)
            raw = io.BytesIO(audio["bytes"])
            with sf.SoundFile(raw) as handle:
                signal = handle.read(dtype="float32", always_2d=True).mean(axis=1)
                rate = handle.samplerate
            sf.write(dest, signal, rate, format="FLAC")
            rows.append(
                {
                    "filepath": str(dest.relative_to(ML_DIR.parent)),
                    "label": 1 if fake else 0,
                    "subclass": ("wavefake_fake" if fake else "wavefake_real"),
                    "partition": "train",
                    "source": "wavefake_hf_mirror",
                }
            )
    provenance = {
        "source": "wavefake_hf_mirror",
        "url": WAVEFAKE_HF,
        "licence": "CC BY-NC-SA 4.0 (WaveFake, research use)",
        "status": "fetched",
        "sha256": sha256_of(parquet_path),
        "rows": len(rows),
    }
    return rows, provenance


# ---------------------------------------------------------------------------
# Source 4: local espeak-ng synthetic fakes (LAST RESORT)
# ---------------------------------------------------------------------------

def fetch_espeak_fallback(max_utterances: int) -> tuple[list[dict], dict | None]:
    """Synthetic fakes via espeak-ng against any cached bona fide speech."""
    if shutil.which("espeak-ng") is None and shutil.which("espeak") is None:
        raise FileNotFoundError("espeak-ng is not installed; synthetic fallback unavailable")
    binary = shutil.which("espeak-ng") or shutil.which("espeak")
    bona_rows = []
    # Reuse any bona fide audio already extracted by an earlier attempt.
    for partition in ("train", "dev"):
        bona_dir = ASVSPOOF_DIR / partition / "bonafide"
        if bona_dir.exists():
            bona_rows.extend(sorted(bona_dir.glob("*")))
    real_dir = DATA_DIR / "espeak_fallback" / "real"
    if not bona_rows and real_dir.exists():
        bona_rows = sorted(real_dir.glob("*.wav"))
    if not bona_rows:
        raise FileNotFoundError("no cached bona fide speech for the espeak-ng fallback")
    rows: list[dict] = []
    fake_dir = DATA_DIR / "espeak_fallback" / "fake"
    fake_dir.mkdir(parents=True, exist_ok=True)
    for index, sentence in enumerate(PIPER_SENTENCES[:max_utterances]):
        dest = fake_dir / f"espeak_{index:04d}.wav"
        if not dest.exists():
            subprocess.run(
                [binary, "-v", "en-us", "-w", str(dest), sentence], check=True, capture_output=True
            )
        rows.append(
            {
                "filepath": str(dest.relative_to(ML_DIR.parent)),
                "label": 1,
                "subclass": "espeak_synthetic_fake",
                "partition": "train",
                "source": "espeak_ng_synthetic",
            }
        )
    for index, bona in enumerate(bona_rows[:max_utterances]):
        dest = real_dir / f"bona_{index:04d}.wav"
        if not dest.exists():
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy(bona, dest)
        rows.append(
            {
                "filepath": str(dest.relative_to(ML_DIR.parent)),
                "label": 0,
                "subclass": "espeak_fallback_real",
                "partition": "train",
                "source": "espeak_ng_synthetic",
            }
        )
    provenance = {
        "source": "espeak_ng_synthetic",
        "url": "local espeak-ng synthesis (formant synthetic speech)",
        "licence": "generated locally — no external data",
        "status": "synthetic_fallback",
        "rows": len(rows),
    }
    return rows, provenance


SOURCES = {
    "official": fetch_official,
    "hf_mirror": fetch_hf_mirror,
    "wavefake": fetch_wavefake,
    "espeak": fetch_espeak_fallback,
}
SOURCE_CHAIN = ["official", "hf_mirror", "wavefake", "espeak"]


# ---------------------------------------------------------------------------
# Optional piper-tts augmentation (modern neural TTS fakes)
# ---------------------------------------------------------------------------

def augment_piper(max_utterances: int) -> tuple[list[dict], dict | None]:
    """Synthesise VITS neural-TTS fakes offline with piper-tts. Never crashes."""
    try:
        import piper  # noqa: F401
    except ImportError:
        print("  piper-tts not installed; attempting uv pip install piper-tts ...")
        try:
            subprocess.run(
                [sys.executable, "-m", "pip", "install", "piper-tts"], check=True, capture_output=True
            )
        except Exception:
            try:
                subprocess.run(["uv", "pip", "install", "piper-tts"], check=True, capture_output=True, cwd=ML_DIR.parent)
            except Exception as exc:
                print(f"  WARN piper-tts install failed ({exc.__class__.__name__}); skipping augmentation")
                return [], None
        try:
            import piper  # noqa: F401
        except ImportError:
            print("  WARN piper-tts still unavailable (no wheel for this Python?); skipping augmentation")
            return [], None
    voice_dir = RAW_DIR / "piper_voice"
    voice_path = voice_dir / "en_US-lessac-medium.onnx"
    try:
        if not voice_path.exists():
            voice_dir.mkdir(parents=True, exist_ok=True)
            base = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/lessac/medium"
            download(f"{base}/en_US-lessac-medium.onnx", voice_path, timeout=300)
            download(f"{base}/en_US-lessac-medium.onnx.json", voice_dir / "en_US-lessac-medium.onnx.json")
    except Exception as exc:
        print(f"  WARN piper voice download failed ({exc.__class__.__name__}); skipping augmentation")
        return [], None
    try:
        import soundfile as sf

        from piper import PiperVoice

        voice = PiperVoice.load(str(voice_path))
        rows: list[dict] = []
        out_dir = DATA_DIR / "piper_tts" / "fake"
        out_dir.mkdir(parents=True, exist_ok=True)
        for index, sentence in enumerate(PIPER_SENTENCES[:max_utterances]):
            dest = out_dir / f"piper_{index:04d}.wav"
            if not dest.exists():
                with sf.SoundFile(str(dest), mode="w", samplerate=voice.config.sample_rate, channels=1, subtype="PCM_16") as fh:
                    voice.synthesize(sentence, fh)
            rows.append(
                {
                    "filepath": str(dest.relative_to(ML_DIR.parent)),
                    "label": 1,
                    "subclass": "piper_tts",
                    "partition": "train",
                    "source": "piper_tts_vits",
                }
            )
    except Exception as exc:
        print(f"  WARN piper synthesis failed ({exc.__class__.__name__}: {exc}); skipping augmentation")
        return [], None
    provenance = {
        "source": "piper_tts_vits",
        "url": "https://huggingface.co/rhasspy/piper-voices (en_US-lessac-medium)",
        "licence": "MIT — piper voices; sentences public domain",
        "status": "fetched",
        "rows": len(rows),
    }
    return rows, provenance


# ---------------------------------------------------------------------------
# Real-world gate split (evaluation ONLY — never trained on)
# ---------------------------------------------------------------------------

def setup_real_world_split() -> dict:
    fake_dir = REAL_WORLD_DIR / "fake"
    real_dir = REAL_WORLD_DIR / "real"
    fake_dir.mkdir(parents=True, exist_ok=True)
    real_dir.mkdir(parents=True, exist_ok=True)
    copied = []
    for candidate in ERCV_CANDIDATES:
        if candidate.exists():
            dest = fake_dir / "ercv.mp3"
            if not dest.exists():
                shutil.copy(candidate, dest)
            copied.append(str(dest))
            break
    note = (
        "User-contributed ElevenLabs clips (fake/) and voice memos (real/). "
        "NEVER used for training — evaluation-only gate split."
    )
    (REAL_WORLD_DIR / "README.md").write_text(
        f"# Real-world audio gate split\n\n{note}\n\n"
        "Gate metrics reported in ml/models/audio_v1_metrics.json.\n",
        encoding="utf-8",
    )
    return {
        "fake_clips": sorted(p.name for p in fake_dir.iterdir() if p.is_file()),
        "real_clips": sorted(p.name for p in real_dir.iterdir() if p.is_file()),
        "ercv_copied": bool(copied),
        "note": note,
    }


def export_real_speech_sample() -> str | None:
    """Copy one bona fide ASVspoof DEV utterance to evidence/media/real_speech.wav."""
    import soundfile as sf

    candidates = sorted((ASVSPOOF_DIR / "dev" / "bonafide").glob("*.flac")) if (ASVSPOOF_DIR / "dev" / "bonafide").exists() else []
    if not candidates:
        print("  WARN no bona fide dev utterance available for real_speech.wav")
        return None
    dest = EVIDENCE_MEDIA / "real_speech.wav"
    signal, rate = sf.read(candidates[0], dtype="float32")
    sf.write(dest, signal, rate, subtype="PCM_16")
    return str(dest)


# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--max-utterances", type=int, default=2000, help="per-class cap (bonafide / spoof / per attack)")
    parser.add_argument("--augment-piper", action="store_true", help="optional piper-tts VITS fake augmentation")
    parser.add_argument("--source", choices=["auto", *SOURCE_CHAIN], default="auto")
    args = parser.parse_args()

    DATA_DIR.mkdir(parents=True, exist_ok=True)
    RAW_DIR.mkdir(parents=True, exist_ok=True)

    manifest_path = DATA_DIR / "manifest.csv"
    existing_rows: list[dict] = []
    if manifest_path.exists():
        with manifest_path.open(newline="", encoding="utf-8") as fh:
            existing_rows = [row for row in csv.DictReader(fh) if row.get("filepath")]
    already_fetched = {row["source"] for row in existing_rows} - {"piper_tts_vits", "espeak_ng_synthetic"}

    rows = list(existing_rows)
    provenance_entries: dict[str, dict] = {}
    prov_path = DATA_DIR / "provenance.json"
    if prov_path.exists():
        provenance_entries = json.loads(prov_path.read_text(encoding="utf-8")).get("sources", {})

    chain = SOURCE_CHAIN if args.source == "auto" else [args.source]
    if args.source == "auto" and (RAW_DIR / "la_train.parquet").exists():
        # The research parquet mirror of the same ASVspoof 2019 LA data is
        # already on disk — skip the 7.6 GB official zip attempt.
        chain = ["hf_mirror", "wavefake", "espeak"]
    for source in chain:
        if source in already_fetched:
            print(f"  {source}: already recorded in the manifest, skipping")
            continue
        print(f"  trying source: {source}")
        try:
            fetched, prov = SOURCES[source](args.max_utterances)
        except Exception as exc:
            print(f"  WARN source {source} failed: {exc.__class__.__name__}: {exc}")
            continue
        if fetched:
            rows.extend(fetched)
            provenance_entries[source] = prov
            print(f"  {source}: {len(fetched)} utterances fetched")
            break

    if args.augment_piper:
        piper_rows, piper_prov = augment_piper(args.max_utterances)
        if piper_rows:
            piper_sources = {r["filepath"] for r in existing_rows if r["source"] == "piper_tts_vits"}
            rows.extend(r for r in piper_rows if r["filepath"] not in piper_sources)
            provenance_entries["piper_tts_vits"] = piper_prov

    if not rows:
        print("FAIL: no audio data could be fetched from any source in the chain")
        return 1

    # Deduplicate by filepath, write the manifest.
    unique = {r["filepath"]: r for r in rows}
    rows = list(unique.values())
    with manifest_path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=["filepath", "label", "subclass", "partition", "source"])
        writer.writeheader()
        writer.writerows(sorted(rows, key=lambda r: r["filepath"]))

    real_world = setup_real_world_split()
    real_speech = export_real_speech_sample()
    provenance_entries["real_world_gate_split"] = {
        "source": "user-contributed clips",
        "path": str(REAL_WORLD_DIR.relative_to(REPO_ROOT)),
        "licence": "user-contributed (evaluation-only; NEVER trained on)",
        "status": "fetched",
        **real_world,
    }
    if real_speech:
        provenance_entries["real_speech_sample"] = {
            "source": "ASVspoof 2019 LA dev bonafide utterance",
            "path": str(real_speech),
            "status": "fetched",
        }
    prov_doc = {
        "version": 1,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "licence_note": "ASVspoof 2019 is released under the Open Data Commons Attribution Licence (ODC-By) 1.0 for academic/research use.",
        "sources": provenance_entries,
    }
    prov_path.write_text(json.dumps(prov_doc, indent=2), encoding="utf-8")

    counts: dict[str, int] = {}
    for row in rows:
        counts[row["subclass"]] = counts.get(row["subclass"], 0) + 1
    print(f"\nmanifest: {len(rows)} utterances across {len(counts)} subclasses")
    for subclass in sorted(counts):
        print(f"  {subclass:40s} {counts[subclass]:5d}")
    print(f"real-world gate split: fake={real_world['fake_clips']} real={real_world['real_clips']}")
    print(f"provenance: {prov_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
