"""baseline

Revision ID: 1284c90c101c
Revises: 
Create Date: 2026-09-13 02:15:29.869467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1284c90c101c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS cyberguard")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response_catalog',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('automation_level', sa.String(length=32), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action'),
    schema='cyberguard'
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_single_user', sa.Boolean(), nullable=False),
    sa.Column('active_organization_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='cyberguard'
    )
    op.create_index(op.f('ix_cyberguard_users_email'), 'users', ['email'], unique=False, schema='cyberguard')
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('is_personal', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['cyberguard.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='cyberguard'
    )
    op.create_index(op.f('ix_cyberguard_organizations_slug'), 'organizations', ['slug'], unique=True, schema='cyberguard')
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('resource', sa.String(length=255), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['cyberguard.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='cyberguard'
    )
    op.create_index(op.f('ix_cyberguard_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False, schema='cyberguard')
    op.create_index(op.f('ix_cyberguard_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False, schema='cyberguard')
    op.create_index(op.f('ix_cyberguard_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False, schema='cyberguard')
    op.create_table('enforcement_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('phishing_high_threshold', sa.Integer(), nullable=False),
    sa.Column('phishing_medium_threshold', sa.Integer(), nullable=False),
    sa.Column('deepfake_high_threshold', sa.Integer(), nullable=False),
    sa.Column('deepfake_medium_threshold', sa.Integer(), nullable=False),
    sa.Column('ato_high_threshold', sa.Integer(), nullable=False),
    sa.Column('ato_medium_threshold', sa.Integer(), nullable=False),
    sa.Column('network_high_threshold', sa.Integer(), nullable=False),
    sa.Column('network_medium_threshold', sa.Integer(), nullable=False),
    sa.Column('impersonation_high_threshold', sa.Integer(), nullable=False),
    sa.Column('impersonation_medium_threshold', sa.Integer(), nullable=False),
    sa.Column('action_on_critical', sa.String(length=64), nullable=False),
    sa.Column('action_on_high', sa.String(length=64), nullable=False),
    sa.Column('action_on_medium', sa.String(length=64), nullable=False),
    sa.Column('action_on_low', sa.String(length=64), nullable=False),
    sa.Column('auto_execute_critical', sa.Boolean(), nullable=False),
    sa.Column('auto_execute_high', sa.Boolean(), nullable=False),
    sa.Column('auto_execute_medium', sa.Boolean(), nullable=False),
    sa.Column('auto_execute_low', sa.Boolean(), nullable=False),
    sa.Column('notify_soc_on_critical', sa.Boolean(), nullable=False),
    sa.Column('notify_soc_on_high', sa.Boolean(), nullable=False),
    sa.Column('notify_user_on_medium', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['cyberguard.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='cyberguard'
    )
    op.create_index(op.f('ix_cyberguard_enforcement_policies_is_active'), 'enforcement_policies', ['is_active'], unique=False, schema='cyberguard')
    op.create_index(op.f('ix_cyberguard_enforcement_policies_organization_id'), 'enforcement_policies', ['organization_id'], unique=False, schema='cyberguard')
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('raw_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['cyberguard.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='cyberguard'
    )
    op.create_index(op.f('ix_cyberguard_events_created_at'), 'events', ['created_at'], unique=False, schema='cyberguard')
    op.create_index(op.f('ix_cyberguard_events_organization_id'), 'events', ['organization_id'], unique=False, schema='cyberguard')
    op.create_index(op.f('ix_cyberguard_events_status'), 'events', ['status'], unique=False, schema='cyberguard')
    op.create_table('incidents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['cyberguard.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='cyberguard'
    )
    op.create_index(op.f('ix_cyberguard_incidents_created_at'), 'incidents', ['created_at'], unique=False, schema='cyberguard')
    op.create_index(op.f('ix_cyberguard_incidents_organization_id'), 'incidents', ['organization_id'], unique=False, schema='cyberguard')
    op.create_index(op.f('ix_cyberguard_incidents_status'), 'incidents', ['status'], unique=False, schema='cyberguard')
    op.create_table('organization_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['cyberguard.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['cyberguard.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_org_user'),
    schema='cyberguard'
    )
    op.create_index(op.f('ix_cyberguard_organization_members_organization_id'), 'organization_members', ['organization_id'], unique=False, schema='cyberguard')
    op.create_index(op.f('ix_cyberguard_organization_members_user_id'), 'organization_members', ['user_id'], unique=False, schema='cyberguard')
    op.create_table('response_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('catalog_id', sa.String(length=36), nullable=True),
    sa.Column('action_name', sa.String(length=255), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('executed_by', sa.String(length=255), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['cyberguard.response_catalog.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['cyberguard.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='cyberguard'
    )
    op.create_index(op.f('ix_cyberguard_response_executions_created_at'), 'response_executions', ['created_at'], unique=False, schema='cyberguard')
    op.create_index(op.f('ix_cyberguard_response_executions_organization_id'), 'response_executions', ['organization_id'], unique=False, schema='cyberguard')
    op.create_index(op.f('ix_cyberguard_response_executions_status'), 'response_executions', ['status'], unique=False, schema='cyberguard')
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('event_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('module', sa.String(length=64), nullable=False),
    sa.Column('threat_type', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('indicators', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('mitre', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('target_user', sa.String(length=255), nullable=True),
    sa.Column('target_service', sa.String(length=255), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['cyberguard.events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['cyberguard.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='cyberguard'
    )
    op.create_index(op.f('ix_cyberguard_alerts_created_at'), 'alerts', ['created_at'], unique=False, schema='cyberguard')
    op.create_index(op.f('ix_cyberguard_alerts_event_id'), 'alerts', ['event_id'], unique=False, schema='cyberguard')
    op.create_index(op.f('ix_cyberguard_alerts_module'), 'alerts', ['module'], unique=False, schema='cyberguard')
    op.create_index(op.f('ix_cyberguard_alerts_organization_id'), 'alerts', ['organization_id'], unique=False, schema='cyberguard')
    op.create_index(op.f('ix_cyberguard_alerts_severity'), 'alerts', ['severity'], unique=False, schema='cyberguard')
    op.create_index(op.f('ix_cyberguard_alerts_status'), 'alerts', ['status'], unique=False, schema='cyberguard')
    op.create_index(op.f('ix_cyberguard_alerts_target_service'), 'alerts', ['target_service'], unique=False, schema='cyberguard')
    op.create_index(op.f('ix_cyberguard_alerts_target_user'), 'alerts', ['target_user'], unique=False, schema='cyberguard')
    op.create_table('incident_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['cyberguard.incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='cyberguard'
    )
    op.create_index(op.f('ix_cyberguard_incident_events_created_at'), 'incident_events', ['created_at'], unique=False, schema='cyberguard')
    op.create_index(op.f('ix_cyberguard_incident_events_incident_id'), 'incident_events', ['incident_id'], unique=False, schema='cyberguard')
    op.create_table('media_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('file_type', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('file_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['cyberguard.events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='cyberguard'
    )
    op.create_index(op.f('ix_cyberguard_media_files_event_id'), 'media_files', ['event_id'], unique=False, schema='cyberguard')
    op.create_table('action_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('alert_id', sa.String(length=36), nullable=True),
    sa.Column('event_id', sa.String(length=36), nullable=True),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('target', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('execution_mode', sa.String(length=16), nullable=False),
    sa.Column('triggered_by', sa.String(length=64), nullable=False),
    sa.Column('triggered_by_id', sa.String(length=64), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('threat_type', sa.String(length=64), nullable=False),
    sa.Column('module', sa.String(length=64), nullable=False),
    sa.Column('policy_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['cyberguard.alerts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['cyberguard.events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['cyberguard.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['cyberguard.enforcement_policies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='cyberguard'
    )
    op.create_index(op.f('ix_cyberguard_action_executions_action_type'), 'action_executions', ['action_type'], unique=False, schema='cyberguard')
    op.create_index(op.f('ix_cyberguard_action_executions_alert_id'), 'action_executions', ['alert_id'], unique=False, schema='cyberguard')
    op.create_index(op.f('ix_cyberguard_action_executions_created_at'), 'action_executions', ['created_at'], unique=False, schema='cyberguard')
    op.create_index(op.f('ix_cyberguard_action_executions_event_id'), 'action_executions', ['event_id'], unique=False, schema='cyberguard')
    op.create_index(op.f('ix_cyberguard_action_executions_organization_id'), 'action_executions', ['organization_id'], unique=False, schema='cyberguard')
    op.create_index(op.f('ix_cyberguard_action_executions_status'), 'action_executions', ['status'], unique=False, schema='cyberguard')
    op.create_table('incident_alerts',
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['cyberguard.alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['cyberguard.incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('incident_id', 'alert_id'),
    schema='cyberguard'
    )
    op.create_index(op.f('ix_cyberguard_incident_alerts_alert_id'), 'incident_alerts', ['alert_id'], unique=False, schema='cyberguard')
    op.create_table('recommended_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('automation_level', sa.String(length=32), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('executed', sa.Boolean(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['cyberguard.alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='cyberguard'
    )
    op.create_index(op.f('ix_cyberguard_recommended_actions_alert_id'), 'recommended_actions', ['alert_id'], unique=False, schema='cyberguard')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cyberguard_recommended_actions_alert_id'), table_name='recommended_actions', schema='cyberguard')
    op.drop_table('recommended_actions', schema='cyberguard')
    op.drop_index(op.f('ix_cyberguard_incident_alerts_alert_id'), table_name='incident_alerts', schema='cyberguard')
    op.drop_table('incident_alerts', schema='cyberguard')
    op.drop_index(op.f('ix_cyberguard_action_executions_status'), table_name='action_executions', schema='cyberguard')
    op.drop_index(op.f('ix_cyberguard_action_executions_organization_id'), table_name='action_executions', schema='cyberguard')
    op.drop_index(op.f('ix_cyberguard_action_executions_event_id'), table_name='action_executions', schema='cyberguard')
    op.drop_index(op.f('ix_cyberguard_action_executions_created_at'), table_name='action_executions', schema='cyberguard')
    op.drop_index(op.f('ix_cyberguard_action_executions_alert_id'), table_name='action_executions', schema='cyberguard')
    op.drop_index(op.f('ix_cyberguard_action_executions_action_type'), table_name='action_executions', schema='cyberguard')
    op.drop_table('action_executions', schema='cyberguard')
    op.drop_index(op.f('ix_cyberguard_media_files_event_id'), table_name='media_files', schema='cyberguard')
    op.drop_table('media_files', schema='cyberguard')
    op.drop_index(op.f('ix_cyberguard_incident_events_incident_id'), table_name='incident_events', schema='cyberguard')
    op.drop_index(op.f('ix_cyberguard_incident_events_created_at'), table_name='incident_events', schema='cyberguard')
    op.drop_table('incident_events', schema='cyberguard')
    op.drop_index(op.f('ix_cyberguard_alerts_target_user'), table_name='alerts', schema='cyberguard')
    op.drop_index(op.f('ix_cyberguard_alerts_target_service'), table_name='alerts', schema='cyberguard')
    op.drop_index(op.f('ix_cyberguard_alerts_status'), table_name='alerts', schema='cyberguard')
    op.drop_index(op.f('ix_cyberguard_alerts_severity'), table_name='alerts', schema='cyberguard')
    op.drop_index(op.f('ix_cyberguard_alerts_organization_id'), table_name='alerts', schema='cyberguard')
    op.drop_index(op.f('ix_cyberguard_alerts_module'), table_name='alerts', schema='cyberguard')
    op.drop_index(op.f('ix_cyberguard_alerts_event_id'), table_name='alerts', schema='cyberguard')
    op.drop_index(op.f('ix_cyberguard_alerts_created_at'), table_name='alerts', schema='cyberguard')
    op.drop_table('alerts', schema='cyberguard')
    op.drop_index(op.f('ix_cyberguard_response_executions_status'), table_name='response_executions', schema='cyberguard')
    op.drop_index(op.f('ix_cyberguard_response_executions_organization_id'), table_name='response_executions', schema='cyberguard')
    op.drop_index(op.f('ix_cyberguard_response_executions_created_at'), table_name='response_executions', schema='cyberguard')
    op.drop_table('response_executions', schema='cyberguard')
    op.drop_index(op.f('ix_cyberguard_organization_members_user_id'), table_name='organization_members', schema='cyberguard')
    op.drop_index(op.f('ix_cyberguard_organization_members_organization_id'), table_name='organization_members', schema='cyberguard')
    op.drop_table('organization_members', schema='cyberguard')
    op.drop_index(op.f('ix_cyberguard_incidents_status'), table_name='incidents', schema='cyberguard')
    op.drop_index(op.f('ix_cyberguard_incidents_organization_id'), table_name='incidents', schema='cyberguard')
    op.drop_index(op.f('ix_cyberguard_incidents_created_at'), table_name='incidents', schema='cyberguard')
    op.drop_table('incidents', schema='cyberguard')
    op.drop_index(op.f('ix_cyberguard_events_status'), table_name='events', schema='cyberguard')
    op.drop_index(op.f('ix_cyberguard_events_organization_id'), table_name='events', schema='cyberguard')
    op.drop_index(op.f('ix_cyberguard_events_created_at'), table_name='events', schema='cyberguard')
    op.drop_table('events', schema='cyberguard')
    op.drop_index(op.f('ix_cyberguard_enforcement_policies_organization_id'), table_name='enforcement_policies', schema='cyberguard')
    op.drop_index(op.f('ix_cyberguard_enforcement_policies_is_active'), table_name='enforcement_policies', schema='cyberguard')
    op.drop_table('enforcement_policies', schema='cyberguard')
    op.drop_index(op.f('ix_cyberguard_audit_logs_user_id'), table_name='audit_logs', schema='cyberguard')
    op.drop_index(op.f('ix_cyberguard_audit_logs_organization_id'), table_name='audit_logs', schema='cyberguard')
    op.drop_index(op.f('ix_cyberguard_audit_logs_created_at'), table_name='audit_logs', schema='cyberguard')
    op.drop_table('audit_logs', schema='cyberguard')
    op.drop_index(op.f('ix_cyberguard_organizations_slug'), table_name='organizations', schema='cyberguard')
    op.drop_table('organizations', schema='cyberguard')
    op.drop_index(op.f('ix_cyberguard_users_email'), table_name='users', schema='cyberguard')
    op.drop_table('users', schema='cyberguard')
    op.drop_table('response_catalog', schema='cyberguard')
    op.execute("DROP SCHEMA IF EXISTS cyberguard CASCADE")
    # ### end Alembic commands ###
